/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 23.08.2026 19:43:22

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1504;
#else
constexpr int kTensorArenaSize = 480;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,114 } };
const TfArray<1, float> quant0_scale = { 1, { 0.31190639734268188, } };
const TfArray<1, int> quant0_zero = { 1, { -98 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { 59, 63, -141, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00071737676626071334, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*20] = { 
  63, 8, 118, -104, -41, 66, 81, -89, -108, 90, 60, -45, 56, -127, 39, 9, -45, -116, 16, 17, 
  61, 64, -40, -103, -122, -2, 45, -74, 13, -38, -26, 59, 10, 52, -17, 81, 66, 105, -65, 41, 
  -91, -18, 115, 34, -86, -94, -106, -74, 100, 41, 106, -88, -71, 92, -6, 14, 14, -23, 9, 99, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,20 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0044733388349413872, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[20] = { 150, 95, 25, -24, 139, 279, 310, -142, -108, 69, -75, 52, 154, 17, 77, 104, -29, 116, -47, -80, };
const TfArray<1, int> tensor_dimension3 = { 1, { 20 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00054172280943021178, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[20*40] = { 
  28, -56, 86, 87, 11, 18, 82, 36, 1, -68, 69, 44, -87, 40, -49, 53, -76, 77, -19, 46, 47, -23, 4, 18, 1, -37, -12, -11, -2, -83, 86, 1, -20, -29, -76, 5, 67, 88, 30, -20, 
  -46, 41, 62, -40, -96, -40, 83, 47, -37, -62, 3, -79, 85, -55, -83, 76, -29, 8, -19, 53, 34, -7, -72, 58, 76, -108, -28, 2, 34, 50, -51, 52, 64, 90, 14, -67, 64, 18, -60, -15, 
  -15, 13, -56, -27, -16, 25, -48, 11, 64, -62, -39, 1, 99, -32, 54, 15, -36, 22, -39, -55, 71, 84, 78, -90, 81, -2, 74, 81, -36, 53, -30, 84, -16, 73, -35, -66, 21, 87, -28, -2, 
  58, 110, -64, -44, -42, 76, -80, 22, -20, 106, 85, -42, 21, 18, 22, 57, 46, 36, -90, 32, -11, 5, -68, 29, -71, 50, -36, -38, -53, -21, -51, 13, -66, -24, 9, -58, -15, -91, -84, -35, 
  -45, -73, -45, -27, -39, 69, -12, 16, -37, 54, -77, 62, -10, -20, 54, 28, -75, 42, -43, 9, -10, 85, -24, -18, 80, -41, 57, 13, -11, 15, -24, -73, -28, -68, 51, 93, -15, 121, 66, 48, 
  -70, -69, -10, -5, -63, 59, -20, -26, -28, -63, -87, 42, -8, -9, 24, -87, 8, 34, -48, 25, 85, -63, -62, -76, -31, 83, -35, 49, 54, 19, 127, -76, 39, 57, 16, -25, 31, 71, 41, -34, 
  66, -54, 78, 9, -1, 48, -45, 5, 46, -31, -9, -7, 85, -45, -69, -52, -2, 36, 19, 82, -10, -16, -23, 21, -51, 74, 68, -25, -57, -19, 34, -71, 26, 106, -62, 70, 6, -24, 24, 44, 
  -10, 62, -10, 67, 72, -45, 37, -78, 65, 4, 9, -46, 40, -30, -82, -35, 64, -78, 13, 54, 68, 44, -59, -66, 50, -97, -17, -78, 58, -62, 24, 80, -74, -61, 87, -35, -59, 20, -34, 21, 
  54, 63, 65, -83, -22, 72, -5, -16, -66, -17, 17, 32, 65, 48, 17, -36, 10, -78, 2, -59, -82, -19, 42, 60, 53, 25, -4, 10, -10, 26, 61, 28, -75, 11, 72, 87, 61, -2, -74, -36, 
  35, -11, 40, -15, 87, -46, -60, 55, -15, 22, 85, -72, 56, -41, 92, 42, -26, -66, -22, -24, 93, 5, -73, -11, -11, 24, 74, 17, -52, -49, 75, 63, -39, -82, -37, -91, 51, 41, -59, 19, 
  -57, 23, 8, -80, -40, 14, 37, -51, -20, 35, -73, 22, 27, 68, 79, 62, -72, -74, -8, -53, 22, -17, -72, 32, 61, -59, 85, -79, -36, 59, -73, 20, 30, 49, 43, 7, 24, -87, 35, -40, 
  -90, 41, -21, -74, 7, -40, 51, 60, 27, -49, -46, 35, 14, -56, -71, -18, -76, -16, 51, 5, 62, 31, -4, -43, 31, 24, -14, 16, 13, -73, -26, 41, 0, -14, 3, -16, -40, -34, 35, -73, 
  -83, 57, -32, 16, -8, 39, -75, -46, -74, -75, 52, -93, 1, 43, 83, 46, 55, 48, 37, 27, -48, 62, 43, -72, 13, -50, 87, -10, -10, 2, -82, 31, 1, 119, 7, 21, -51, -61, -45, -75, 
  19, 30, 71, -35, 39, 37, -102, -8, -40, 79, 67, -17, -56, 23, 32, 78, 81, 5, 62, 0, 19, -19, 34, 84, 9, 4, 23, 94, -82, 43, 35, -49, -48, -17, 105, -7, 3, -21, 26, 86, 
  42, -27, 51, 20, 72, 44, 57, -71, 77, 51, -6, -63, -65, 37, -58, 44, -2, 67, -74, 18, -37, 7, -72, 39, 11, -6, -17, 53, 25, -19, 68, 75, -59, 74, -51, 25, 21, -26, 66, -8, 
  50, 71, -112, 60, -59, 46, 89, -55, 47, -24, 66, -8, 13, 4, -81, 49, -81, 49, 79, 96, -30, -10, 44, -63, -18, -24, 55, -72, -17, 31, 14, -73, 58, 66, -32, -93, 40, 75, -51, -53, 
  33, -58, 74, -25, -12, 31, -1, -21, -13, -41, -24, -77, 12, 58, 18, 19, -38, -30, -17, -90, 78, 26, -13, 46, -85, -38, 51, -31, -81, 77, -75, -27, 66, 12, -18, 24, 22, 0, -3, -85, 
  66, 51, 86, -85, -52, 86, 33, 35, 5, 39, 45, -50, 61, 88, -83, -7, -41, -62, 88, -4, 48, -21, -61, -48, -35, -104, -61, -88, -29, 38, -82, 66, 17, -8, -28, 55, -84, -14, -73, 47, 
  35, 40, 6, -20, 28, 16, -93, 79, 53, 7, -75, 53, -58, -83, 4, 90, -10, -62, 66, 77, -37, -29, 30, 82, 68, 109, -77, 42, 65, 67, 119, 18, -79, 52, 46, -10, -13, 86, 63, 50, 
  -52, 17, 62, 8, -86, 37, -46, -3, 67, 76, -87, 15, -58, 6, -59, -54, -23, 86, -35, 40, 41, -79, 48, 87, -17, -33, 14, 75, -61, 80, -62, 66, 25, -21, 35, 51, 76, 54, -30, -15, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 20,40 } };
const TfArray<1, float> quant4_scale = { 1, { 0.003545066574588418, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[40] = { -6, -49, -4, 0, 3, 0, -6, 2, -3, -4, 0, -11, 2, -20, -40, -12, -16, -17, -31, 21, 0, -15, -23, -38, -7, 17, -11, -13, -11, -34, 42, -4, -6, 3, -12, 4, -10, 16, -12, 0, };
const TfArray<1, int> tensor_dimension5 = { 1, { 40 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0011421408271417022, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[40*114] = { 
  -6, -8, 16, 10, 8, -3, -47, -11, 14, -25, 46, 44, -48, -25, -36, 13, 32, -49, -32, -8, 22, -41, -46, -17, -34, -9, 22, -44, 51, 53, 21, 7, -7, 2, 46, 14, -31, -10, 50, -5, 15, -15, -20, -46, -33, 26, -20, 1, 57, -34, 1, 16, -10, -16, -25, 45, 7, -31, -14, -56, 23, 10, -52, 34, 44, -44, 50, 44, 3, -12, 27, -35, -19, -11, -30, -22, -19, 4, 40, -54, 17, -29, -18, -38, 34, -29, -13, -8, 30, -34, 7, -46, 4, -24, 31, 43, 15, 30, -36, -50, -17, 47, 16, 36, 20, 49, -9, -16, -14, -13, 19, 23, 47, -14, 
  -104, 65, 3, 0, 9, -64, -2, 29, 39, 54, -12, 41, 30, -4, -8, -4, 50, 43, -38, -20, -22, 63, 15, 26, -8, -46, 11, 5, -37, 53, -2, -3, 6, 60, 49, 64, 56, 23, -37, -26, -3, -43, 10, -24, -5, 7, 34, -12, -33, -2, -10, -27, -62, 5, -40, -38, 46, -90, 84, -15, 10, -6, 0, -16, -57, -29, 23, 36, -46, -16, -58, -11, -3, 27, -29, -32, -57, -89, 50, -49, -40, 15, -46, -42, -45, -9, 20, -13, 30, -27, -38, 22, -14, -6, 35, -12, 93, 16, -38, -44, 14, -59, -41, 17, 17, -42, -14, -48, 9, -12, -51, 11, 8, -19, 
  12, -42, 26, 26, 42, -59, -46, -37, 12, -4, 46, 23, 1, 45, -33, -33, 21, -17, -50, 30, 3, -59, 20, -23, 26, 35, -4, 32, 9, 9, 47, -8, -14, 11, -17, -9, 7, -7, 3, -16, 10, 10, -16, 60, 13, 7, 54, 93, 51, 51, -20, 2, 48, 72, 26, -6, 24, -32, 62, -31, -30, 49, 55, 24, -35, 39, 16, 35, -21, 37, -4, 52, -39, -41, -16, 29, -25, -44, 13, 39, 1, 17, 4, -17, -12, -39, 8, -14, 37, -20, 36, 4, -29, 30, 29, -3, 59, 6, 13, -34, 54, 15, -41, 20, -46, 41, -17, 37, -41, 49, -2, 30, -29, 8, 
  -44, -28, -4, -5, 26, 43, 26, 23, -41, 18, -35, -34, 32, -38, 44, -24, 44, 32, 52, 10, -44, 1, 51, -2, 32, -35, -10, 13, -46, -22, 48, 50, -35, 30, -34, 30, -29, 11, -13, 19, 11, 37, -10, -5, 32, 21, -44, 44, -32, 42, -17, 43, -25, 6, 9, -45, -2, 3, -48, 37, -49, 2, -45, -1, 13, -20, -14, -10, -35, 4, 32, 13, 10, -22, -18, -14, 43, -34, 19, -29, -18, 44, -28, -18, 20, -50, 0, 31, 18, 38, -13, 45, -1, -8, 3, -8, 2, 2, -22, -32, -25, -33, 3, 3, 49, -3, -3, -14, -48, -43, 51, 39, 53, 39, 
  60, -38, -41, 41, -34, 1, -26, -32, 36, -1, 2, -6, -17, 38, -50, 22, 47, -19, -15, 5, -3, -41, 29, 37, -17, 28, -47, -19, 30, 44, -47, 45, 0, -25, -53, -43, 32, 19, -6, -11, 69, 24, 14, 29, 53, -4, 33, 34, 25, -22, 14, 44, 81, -14, 0, -3, -20, 45, -80, -19, 48, -32, -38, 54, -20, -13, 23, -6, 31, -48, 17, 34, 35, 40, -43, -5, -32, 9, 51, 50, -14, -61, -62, 3, 39, -23, -48, 23, -29, -25, -30, 10, 6, -29, 34, 46, 22, -15, -6, -4, -37, 4, -44, -9, -30, 41, 17, 39, -13, 26, 7, 12, -29, -2, 
  -16, 9, -18, 5, -21, -50, -53, 9, -48, -16, -41, -5, 39, 15, -25, -10, 41, 12, 36, 22, 37, -37, 9, -40, -2, 47, 18, 24, 18, 30, 14, 35, -15, -19, 46, 50, 36, -53, -6, 34, -41, -26, -4, 16, 53, 6, -33, 2, -6, -1, -7, 43, 12, 52, 18, -6, 16, 37, 26, 14, -53, -41, 2, -9, -26, 4, -34, 11, 24, 41, 29, 0, 8, 47, 46, 41, 18, 37, -17, -21, 30, 27, 35, 51, 29, -3, -45, -44, -41, 52, 44, -52, -8, 2, 53, -28, 27, 13, 48, 38, -6, 37, -48, -41, 9, 22, -21, 33, -34, 12, -33, -18, 40, -50, 
  -11, 98, -12, -14, -8, -30, -13, 12, -29, 46, -34, -30, -21, 54, 44, 38, 2, -38, -50, -33, 9, -25, -32, 41, 11, -22, -35, 27, 12, 36, -29, 44, 30, -44, -38, 6, -9, 22, 1, -6, 9, 10, -15, 3, -55, -64, -51, -49, -49, -78, -75, -44, 1, -62, -82, -52, 9, -24, 127, -51, -26, -37, -28, -7, -19, 20, -5, 29, -46, 38, 22, -19, -36, 40, 42, -36, 22, -56, -1, 25, 33, 14, 54, -5, 55, -36, 49, 36, -36, 34, 51, 59, -12, 36, -26, 32, 33, -59, 34, -6, -27, -9, 4, 57, 9, -3, 45, -45, 10, -22, 12, -1, 20, 21, 
  51, 38, 36, 23, -3, -5, -16, -34, -16, -35, 46, -27, -12, -15, -50, 12, 11, -20, -8, 58, -5, 44, 20, 10, -22, -30, -6, -14, -44, 38, -35, 26, 26, 10, -28, -35, -15, -1, -18, -18, 46, 32, 13, 29, 41, -9, 11, -42, -16, 4, -16, -1, -7, -22, 49, -33, 8, 87, 44, -36, -17, -6, 29, -28, -3, 38, -5, -29, -3, 10, -1, 37, 26, 4, 42, 35, 36, 43, -33, -10, -8, 22, -2, -46, -44, 38, -13, -39, -21, -21, 2, -10, -33, 30, 58, -21, 18, -36, 47, -31, -16, -22, 0, -2, -13, -2, -42, 15, 58, -2, -9, 12, 18, -12, 
  29, 31, -47, -7, -5, 5, 32, 10, 23, 54, 50, 49, 34, 39, 45, 31, -7, -43, -46, -36, -28, -47, -48, -20, -27, -48, 54, 28, 8, -4, 35, 46, 4, 47, 34, -21, 10, -16, -39, -30, -25, -43, 44, -1, 32, 1, -47, 42, 50, 25, -36, -23, 7, -12, 15, -23, 10, 41, 17, 45, 36, 2, 29, 11, -47, -47, -53, -36, -37, 14, 46, 38, -42, 23, -47, 48, -29, -25, -51, 29, 30, 10, -13, -44, 13, 46, 9, 47, 43, -53, -45, -37, 1, -39, -47, 27, 1, -41, -7, -49, 39, -16, 16, 8, 44, 51, -38, 44, 50, -50, 41, 8, -25, -34, 
  -54, -52, -20, -59, -43, -54, -56, -34, -5, 39, -12, 11, 55, 4, 0, -22, -38, 39, 36, -28, 19, -13, -28, 28, 36, 22, -54, -33, 30, -50, -49, -34, 5, -45, -31, -29, 52, -8, 25, -56, 40, -53, -58, -59, 5, 23, -31, -6, -3, -44, 23, -58, -3, -61, 21, 25, -23, 10, 66, 53, 40, -29, -40, 30, -34, -32, -26, -53, 39, 2, 35, 13, -1, 41, -60, -59, -60, 47, -21, -48, -15, 12, -7, -29, -12, 3, 26, -58, -4, 31, -61, 21, 16, 45, -18, -29, -25, 19, -25, -57, 14, -45, 11, 29, 33, -7, -1, 3, 21, 25, 4, -60, -42, -11, 
  51, 24, -42, 31, -3, -41, 14, 25, -1, 19, -45, -49, 44, -25, 38, -51, -42, 53, -15, -42, 20, 3, -17, 4, 31, -17, -10, 38, -35, 12, 14, 34, 13, -48, 24, 42, -12, -1, 15, 24, -22, 16, -23, -19, -20, -1, 25, -8, -30, -48, 45, 25, 26, 1, 41, -13, 18, -51, -16, -20, -26, -32, 44, -39, 25, 34, -41, 16, -7, 48, -22, -24, -9, -6, 22, -2, 26, -30, -23, -9, 43, 41, -5, 13, -3, 34, -27, 40, 18, 18, 15, 22, -10, -46, 52, -37, 36, 2, -13, -51, 15, 20, -15, 14, 18, 0, 40, 12, -36, 15, -3, -19, -11, 44, 
  -12, 48, -43, 50, 35, 48, 36, -17, -20, 51, -9, 54, 19, 36, 57, -2, 5, 17, -34, 13, 25, 42, -29, 13, -42, -36, 20, 52, 30, 9, 44, 1, 41, 38, -8, -38, -27, 46, 24, 24, 21, -48, -54, -30, -2, 31, -48, 14, 27, -5, -3, 44, 37, 9, 3, -8, 25, -46, -52, 35, 50, 0, 0, -25, 57, -29, 26, -43, -36, -22, 0, -4, 39, 5, -33, 41, -4, -8, 29, -7, 46, 8, -43, -17, 38, 22, 48, 50, 54, -7, -15, 29, -32, 5, 52, -43, -6, -18, 28, -52, -6, 51, -35, -28, 2, -16, -39, -7, -10, 0, 7, -19, 27, 21, 
  -26, 11, 31, -27, -33, -13, 11, -20, 5, 43, 23, -36, 25, 2, 43, -25, -54, 31, 41, -37, -11, -47, -56, 42, 1, 41, -50, -33, -35, -8, -16, -41, 8, 34, 3, -3, 22, 15, -12, -40, 2, 44, 45, -36, 13, -30, 17, -32, 25, 38, -33, 30, 2, -2, 28, -2, 4, -25, -22, 50, 29, 16, 24, -48, -24, 1, 47, 21, 32, 45, 38, 46, -16, -48, -13, 15, 10, 0, -42, -24, 31, -43, -31, 5, -18, 51, -43, 29, -17, -19, -36, -14, 46, -28, -25, 6, 6, -32, -16, -31, 17, -29, 10, 17, 15, 31, -21, 53, 42, -14, 26, 5, 44, 41, 
  -5, -1, 42, -44, -1, 4, 47, -10, -54, -43, -42, -4, -24, -37, -10, 14, -42, -10, 25, 33, 49, 47, 36, -12, 54, 23, -33, 54, 15, 30, 4, -2, 43, 52, 19, -39, 41, 30, 15, 28, -17, -26, 15, 90, 41, 43, 0, -19, 9, 29, 36, 40, -9, 22, 6, 51, -10, -46, 45, 30, -6, -25, 50, -37, 25, -38, 18, -40, 26, -21, 48, 32, -12, 27, 32, -17, -58, -31, -20, 27, -18, 26, 7, 38, -35, 51, 21, -13, 17, -3, 34, -25, 17, -47, 55, -32, 70, 0, -52, 18, -32, 12, 42, 18, -20, 9, 15, -35, -16, -14, -41, 23, -10, -50, 
  46, -64, 7, -44, 6, 65, -29, -33, -28, 49, 63, -7, -30, 13, 63, 75, -2, 13, -24, 12, -56, -29, -14, -17, -72, -21, 14, -39, 53, 50, 11, -22, 19, 58, 4, 24, 62, 54, -71, -17, 40, -44, 9, -14, -88, -55, -31, -60, 24, 34, -52, -37, -41, 38, -13, -9, 53, -86, 30, 68, -37, -12, -49, -12, 41, -24, -6, 30, 45, -48, -20, -20, 33, 14, 27, -19, 7, 42, 5, -20, 23, -20, -57, 9, 25, 25, -34, -52, 40, 11, -58, -47, 10, 4, 44, -73, -63, 4, -61, 22, 29, 30, -64, -59, -10, 9, -28, -16, -32, -58, -4, -31, 26, -15, 
  2, -31, -54, -11, 14, 3, -23, 31, 14, 24, -44, -39, 17, -19, -7, 18, -15, 0, 5, 5, 28, 18, 31, -56, -40, 23, 39, 24, 49, -37, 4, 13, 12, 12, 9, -41, 47, 25, -29, 41, -34, 3, 49, 4, 27, -4, 9, 50, -45, 28, 41, 52, 38, 10, 54, 17, -51, 23, -17, 4, -31, -7, 20, -30, -14, -9, 12, -35, -28, 8, -27, -21, 45, 52, -3, 28, -31, 27, -23, -29, -30, -43, 5, -46, 35, -10, -29, 29, -5, -44, 55, -34, -13, -7, 2, -54, 15, 32, -49, 10, 40, -7, 41, 24, -32, -5, -21, -13, 38, 3, -26, 7, -28, 27, 
  -1, -27, 43, -27, 6, -44, 18, -13, -37, 28, -39, 25, 28, -4, -32, 25, 47, -11, 21, -56, 0, 18, -14, 34, -14, -1, -12, -8, -6, 35, -33, -26, -31, 9, 8, -34, -18, 44, -51, -36, 20, -56, 1, -16, 35, -6, 41, 0, -3, 41, -15, -13, 43, 22, -10, 30, 36, -93, -9, -19, 22, -35, 43, -12, 43, -14, -13, -42, 31, 46, 40, 26, -32, 45, -7, -33, -5, -11, 47, -38, -44, -22, 30, 37, -20, 17, 16, 14, 18, -59, 32, -53, 43, -41, -57, 11, -39, 71, 7, -23, -42, -48, 37, -55, -41, -51, 25, -28, 39, 31, -52, 41, -10, 26, 
  -14, 45, 34, -27, 13, -14, -14, -33, -32, 55, 34, -34, -24, -22, 1, -2, 7, 10, 56, 34, -48, 48, 12, 7, -35, -19, 55, 21, 45, -6, 22, 31, -6, -1, 23, 46, 39, 30, -48, 43, -46, -53, 21, -16, 17, 5, -44, 44, 28, 53, 52, 9, -25, -37, 20, -43, 47, -33, 35, -24, -38, 8, 6, 30, 56, 33, -27, 9, 56, 17, -48, -44, 33, 21, 51, 31, -49, 16, -7, 16, -47, -46, 49, -42, 50, -46, 42, 46, 16, -13, 59, 53, -41, 53, 15, 38, 2, 49, 10, 17, 5, 13, 20, 25, 31, -39, 0, -4, -20, 16, -7, -3, -32, 1, 
  -96, 93, 13, -30, 15, -78, -55, -48, -6, -37, -39, -41, -30, -8, -55, 18, -42, 46, 9, -52, -51, -29, -10, 41, -28, 23, 42, 50, -21, -3, -11, -22, 39, 58, 13, 35, 54, -39, 67, -40, -6, 32, 3, 73, 19, -31, 50, -19, 49, 63, -48, 8, -36, -39, -9, -42, -43, -72, 99, -28, 40, -16, 8, -9, 7, -43, 5, -8, 13, -19, 41, -4, 49, 18, -6, 0, 37, -91, 16, 38, -1, 31, 0, -7, 13, 57, 64, 2, -19, 54, 36, -35, 47, -40, 5, -28, 72, 20, -32, 20, 33, -10, 2, -25, -4, 5, 44, -18, 51, 1, -20, -7, -4, -28, 
  7, -2, -4, 13, 30, -38, 35, -3, -4, -31, -21, 40, -5, -37, 17, -39, 44, 3, -51, 35, -29, 0, 12, -40, 11, 21, -43, 25, 26, -35, -43, -48, -51, -21, -53, -63, -29, -18, -53, -40, 29, 12, 7, 45, 9, -59, -48, 3, -46, 42, -29, 25, -20, -62, -16, 41, -59, 54, -31, -38, 58, 25, 28, -39, -20, -31, 50, 15, 34, -20, 29, 26, 9, -28, -2, -46, 28, 24, -61, 4, -39, 59, 28, 46, 54, -10, 30, 20, -32, -26, 20, -9, -10, -29, -10, 20, 31, -21, -35, 52, 39, 22, 41, -18, 24, 5, -7, 26, -12, 43, -15, 34, 35, -42, 
  -7, 63, 20, -32, -38, 21, -35, 46, 38, -26, -14, 9, 33, -26, -48, 16, -44, 22, 38, -14, 0, -25, 43, 43, -27, -41, -6, 38, 43, 35, -20, -38, -38, 15, -10, -49, -17, -28, 35, 48, -10, 15, 2, 6, -40, -5, 50, -46, 33, -17, -51, 29, -21, 4, -26, 14, 35, 81, 35, 3, 0, 46, 0, 11, 0, -24, 22, -21, 59, 9, 5, -27, -4, 32, -21, 37, 67, -27, -4, -4, 35, -10, -13, -29, 52, -3, -8, 47, 35, -30, 26, -28, 26, -44, 7, -3, 55, 8, 39, -4, 43, 26, -24, -20, 47, 39, -11, -1, -17, -20, 40, -37, -30, -20, 
  -7, 5, 5, 11, 44, 27, 14, -24, 31, -27, -1, -6, 30, 43, -35, 54, 56, -12, 0, -29, -26, 33, -18, -38, 5, -2, -15, -49, 47, -38, 41, -5, 5, -48, -10, -26, 1, 48, -33, 49, -55, -5, -1, -34, -8, 21, 17, 35, -39, -42, 55, -3, 29, -29, -5, -42, 21, 44, 9, -33, -54, -32, 0, 25, 54, -11, -12, 37, -12, 38, 12, -19, 38, 30, -27, -14, -23, 39, 53, -29, -47, -20, -13, 13, -9, -29, -14, 39, -13, -27, 17, 21, 45, -5, 56, 20, 46, 14, -50, 42, -15, 10, 10, 51, 41, -5, -1, 7, 22, -34, -40, -19, 48, -8, 
  -16, -29, -26, 37, -12, 11, 31, 43, 37, 29, -44, -36, -7, 33, -35, 42, -32, -10, 3, -51, 19, 0, -17, -48, -15, -9, 4, -38, 13, -9, -12, 16, 38, -22, -10, -44, 53, -38, 18, -37, -23, -9, 2, -9, -4, 43, -19, 37, 28, 17, -42, -34, -17, 42, -5, 32, -38, -61, 62, 36, 38, -54, 43, 36, -1, -30, 28, 27, 41, 21, 49, 51, 3, 7, 9, -25, -8, 45, -8, -46, 32, 46, -31, -8, -6, -13, -49, 11, -23, -45, -39, 52, 9, -6, -32, 3, 44, -26, -52, -9, -4, -14, -41, 7, 47, -52, -18, 23, 39, -49, 13, -22, 6, -50, 
  11, 46, 19, 47, -43, 43, 40, -4, -18, 41, 29, -12, 35, 39, 42, 29, -17, 14, -44, 6, 23, 51, -50, -38, 12, -3, -50, -35, -44, -2, 24, 51, -33, -30, -31, -12, -22, 29, 64, 45, 38, -27, -50, -6, -3, 39, 28, 2, 9, 8, 14, -15, 11, 0, 31, 23, 59, 14, 31, 11, 32, 9, -6, -35, 15, -49, 45, -29, 8, 34, 33, -22, 9, -40, -43, -34, 9, -20, 72, -52, 21, 17, 5, -44, 2, -28, -54, 17, 19, -57, 35, 38, -57, 28, -34, -83, 1, 77, -47, -33, -28, -32, -14, 28, -7, 37, -20, -26, -8, -40, 11, -23, -57, -55, 
  9, -36, -39, -15, 29, 12, -22, 31, 37, -10, 51, -7, 4, 38, -40, -32, -36, -24, -47, 29, 16, -17, -35, 30, 38, 41, -12, 53, 43, 33, -41, 51, 32, 55, -11, 16, 20, 27, -17, -22, -49, -40, -33, -37, -18, 3, 36, 3, -10, -40, -45, -14, -26, -12, 19, -1, 0, -6, -37, -5, -17, -9, 5, -39, 24, -7, -8, -10, 29, 40, 10, 7, -49, 11, -45, 27, -37, 53, -27, -42, 31, -10, -33, -17, -14, -48, 32, 9, 30, 18, 6, 19, -41, -33, -32, -23, -35, 42, -13, -34, 52, -46, -45, -6, 6, 29, 20, 14, -48, 29, -10, -12, 39, 44, 
  94, -26, -49, 52, 3, 11, 39, 10, 27, 15, -29, -13, -6, -1, 60, 1, -25, -44, -22, 48, 22, -7, -51, -37, 26, -16, -30, 24, -13, -3, -54, -48, -6, 38, 21, -22, -48, -42, 6, 19, 43, 45, -37, 17, 8, 24, 65, 14, 30, 50, 40, -1, 37, 0, 60, 21, 41, 61, -98, -49, 32, 8, 58, -15, -44, 21, -17, 52, -36, 50, -1, -30, -32, 47, -24, 16, -58, 28, 49, 14, -22, -60, -69, -43, -11, 30, -13, 4, -28, 11, 5, -53, -38, -36, -57, 63, -38, -35, -7, -10, 23, 33, -46, -17, 33, -20, -21, -47, 42, -51, 50, -29, 18, -18, 
  -18, -28, -53, 35, 1, -1, 34, -5, -24, 44, 14, 38, -2, -41, 17, -46, -3, 34, 25, 53, 9, 0, -48, -31, -7, 48, 37, -2, 48, -15, 9, -29, 17, 37, -26, 50, 28, 35, 42, -25, 30, 12, -17, 17, -19, 37, 53, -47, -28, -1, -27, -11, -4, -32, 1, 32, -49, -11, -24, -21, 8, -2, -39, 27, -41, -46, 29, 46, 28, 57, 35, -49, 10, -43, 38, 49, 46, -50, -23, -29, 17, -34, -18, 34, 15, 42, 58, -40, -18, -8, -14, 6, -45, -40, -44, -32, -15, -16, 43, -4, -26, -24, 52, 8, 53, 27, -21, -22, 1, 21, 57, -7, -38, 57, 
  -48, 24, 14, 21, 48, 53, 26, -46, -23, 55, -30, 4, 56, 19, -3, 54, -42, -45, 19, -40, 5, 65, -12, -51, 15, -20, 5, -34, 38, -53, -15, -34, 20, -16, 60, 17, 28, 13, 25, 20, -45, -8, -56, 18, -20, -44, -27, -19, -44, 52, 36, -42, -13, -41, -13, -37, 31, -50, -19, 38, 12, -44, 11, -51, -15, -9, 3, 26, -18, -10, 25, 38, 28, -45, 5, -28, 1, 35, 22, -16, -37, -23, -29, 12, -21, -26, -3, 20, -60, -15, 36, -36, 2, 32, -9, -44, 38, 36, 27, 9, -16, 0, 37, -39, -16, -38, -10, 14, -58, 32, 5, 28, -28, -13, 
  60, -16, 25, -35, -12, 50, -9, -13, -16, 20, 46, 31, 43, 4, -38, -41, 9, -6, 53, 11, -24, -28, 12, -10, 29, -45, -28, 31, 30, -13, -5, -19, -49, 39, -27, -13, -42, -44, -62, 39, -30, -27, 10, -19, -3, -76, -37, -24, -6, -46, -46, 11, 29, -3, -13, 30, 13, 58, -48, -5, 38, -22, -38, 60, 49, 49, -6, 8, 57, 54, 7, -20, 17, -26, -22, 38, -23, 58, -49, -15, -3, -27, -38, 27, 22, 4, 53, -11, -7, 30, -9, -8, 34, -9, 38, 41, -5, 17, -26, 38, 34, -1, -2, -35, 36, -21, -8, 26, -40, 39, 40, -6, -37, -40, 
  11, 14, 20, 2, -42, -39, -10, 47, 36, -29, 38, 54, 41, 20, 28, -12, 2, 20, 45, -22, 13, 22, -66, 9, -52, 50, -47, 16, 14, 21, -24, 53, 2, 1, 40, 51, 18, -30, 0, 30, 56, -42, 30, -15, 27, 41, 14, 69, -31, -5, -24, -4, 11, -11, 34, -15, -5, 6, 55, 41, -61, 40, 16, -21, 19, -33, -18, 21, -5, -56, -40, -5, 16, -9, -9, -51, -77, -79, 46, -17, -56, 9, -61, -34, -38, 33, -24, -39, -43, -14, -5, 36, -43, 32, -6, -67, 80, -18, -29, -19, 0, -24, 23, -47, -8, -13, 34, -20, 41, 7, 11, -59, -37, -23, 
  82, -101, -41, 17, 17, 52, -32, -26, 6, 16, 35, 49, -11, -19, 34, -45, -14, 43, -41, 29, 32, -36, 49, -40, 11, -50, -21, 30, -39, -26, 8, 19, -67, 11, 4, 2, -45, 31, -23, 114, 46, -28, 40, 38, 2, 71, -4, 16, 30, 42, 57, 56, 11, -7, 43, 24, 35, 93, -41, -67, -28, -22, 44, 21, -41, -16, -47, 26, -41, 34, -38, 15, -51, -20, -17, 31, 53, 54, 20, 24, -11, 8, -12, -47, -13, -35, -62, 36, -12, 31, -60, -56, 26, 21, -11, -23, -105, 14, -22, -9, 51, -22, 26, 29, -14, -22, 18, -36, 45, -5, -5, -45, 15, 5, 
  17, -15, -46, -22, -14, 50, 50, 26, -17, 3, -10, 3, 22, 27, 22, -10, -21, -11, 15, 27, 37, -9, -18, 23, -3, 37, 19, 32, -8, -42, 30, -13, 33, -12, -11, 3, -31, 16, 42, 8, 47, -30, -47, 26, 36, -41, -39, 17, 37, -13, -2, 39, 22, 54, -44, 13, 18, -35, 3, 17, 46, -12, -13, -39, 41, 33, -10, 13, 42, 32, 8, 24, -47, -20, -26, -29, 4, 18, 53, -13, -16, 29, 25, -31, 11, 5, -22, 2, 55, 45, 47, 39, 19, 21, 39, -16, -51, 43, 32, -28, -41, -35, 26, -40, -2, -3, 11, -29, -16, 40, 43, -19, 5, -24, 
  -53, -16, -45, -54, 24, -47, 31, 41, -16, -13, 32, 35, -15, -24, -12, 15, 50, 35, -33, -35, 6, -27, -23, 28, 55, -45, 12, -50, 18, 25, -37, 37, 15, 22, 38, -23, 36, -51, 40, -48, 21, 33, 40, -29, 34, 50, 11, -46, 7, -10, 33, 19, -43, 44, 10, -16, -24, 8, -19, 26, -7, -30, 24, 31, 47, 31, -1, 51, 0, 56, 13, -12, -13, 39, -51, -37, 16, 50, 29, -28, -18, -19, -50, 55, -27, -32, 20, 33, 12, -51, -11, -6, -37, -44, -37, 51, 34, 51, 13, -29, 28, 47, -46, 54, -3, -48, 34, 40, -24, -17, 53, -14, 49, -14, 
  -25, -36, 47, 42, 1, 33, 24, -28, 1, -11, -32, -7, -43, 56, 15, -40, -40, 25, 4, -9, 27, -47, -25, 31, 40, 23, -28, -23, 35, -7, -15, -44, 37, 37, 45, -11, -13, -40, -75, -30, 13, -7, 29, -15, -104, -36, -13, -77, 12, -58, 19, -64, 4, -24, 7, -60, -8, 37, -65, -31, -23, -25, 17, 44, 46, -40, 2, -45, -15, 47, -3, -47, 42, -22, 55, -37, -23, 100, -10, -24, 32, 26, 12, -39, -13, -14, 22, -33, 43, 6, -34, 14, 27, 11, 41, -29, -25, -2, -5, -44, 19, 35, 24, -21, 37, 63, -25, 52, -12, 54, 54, 57, 26, 28, 
  -63, 10, -20, 12, 12, -64, 49, -21, 7, -41, 49, 41, -29, -40, -11, -24, 37, -28, 13, -79, 39, 50, 28, -37, -37, 16, -13, -36, -12, -31, 23, 54, 55, 42, 38, -24, -12, 30, -4, -2, 11, -24, -35, -17, -17, -7, 8, -16, 43, 50, 39, 26, -29, -56, -32, 1, 33, -22, -12, 72, -9, -29, -58, 39, -47, -42, -11, 17, 13, 34, 11, -36, 26, -44, 29, -48, -17, -30, 54, -50, 26, -22, -39, 2, -37, 16, -40, 16, 22, 22, -45, -10, 5, 7, 9, -50, 38, 7, 4, 31, -71, -38, 18, -31, 10, 18, -25, 29, -61, 1, 40, 18, 36, -20, 
  30, -48, 19, 3, 7, 8, 18, 35, 18, 26, 37, 18, -5, -25, -35, -24, 23, 6, -54, 54, -40, -45, -33, -15, 47, 1, 49, -29, 24, 46, -35, -26, 18, -36, 29, 37, 43, 37, 37, 4, -48, 43, 23, 78, 94, 84, 63, 65, 51, 44, 66, 3, -20, 38, -19, -35, 20, -29, -41, -5, 13, -15, -5, -18, -32, -10, 49, -15, -12, 13, 19, 0, 13, 10, -38, -16, 47, 4, 22, -47, 43, 45, -5, 45, 15, -19, -26, 58, -43, -3, -15, -23, 15, -15, -46, 38, 3, -44, -43, 20, 59, -7, 5, 46, -40, -24, 52, 50, 34, -30, -40, 37, 13, 13, 
  -37, -5, -15, -42, -50, -14, 29, 23, -24, -14, -28, -20, -15, 44, 42, 3, -29, -25, -43, -1, -8, 35, -44, -47, -18, -4, -36, -48, -8, -34, 49, 6, 27, -17, 54, -8, 49, 31, 12, 11, 44, -20, 33, -29, -10, 55, 12, -22, -13, -22, -4, -5, 41, 53, -29, 16, -47, 17, 44, -44, -11, -9, 14, -44, 51, 46, 15, 4, -34, -45, -10, -19, 21, 36, 11, -6, 22, -23, 47, -17, 15, 44, -28, -47, 13, -8, 41, -12, 41, 50, -21, 27, -25, 34, 28, -52, 49, 35, -32, 11, 34, -17, 24, -4, -18, 55, 9, -32, 1, 18, -3, -46, 2, -16, 
  78, -10, -26, 47, -10, 85, 52, -7, 26, -19, -7, 67, -34, 24, -24, -34, 20, 58, -20, -41, -3, -15, -31, 54, 19, -40, 19, -48, -54, -33, -45, 43, 22, -3, -18, -17, 37, 6, -16, 39, 28, 12, 51, 48, 60, 83, 3, 49, 3, -26, 47, -4, -25, 84, -23, -5, 20, 69, -8, -30, 53, 51, 35, 52, 53, 29, 46, -4, 37, -8, -46, 39, 0, 23, 0, 49, -43, 73, 36, -14, -28, -13, 28, -35, -1, -26, 30, 37, 1, 30, 39, -30, 22, -18, -51, 54, -9, -40, 43, -34, -22, -35, -27, -16, -25, -3, 1, 26, -46, -48, -17, -20, -4, -36, 
  -17, -52, 1, -9, -21, -17, -34, -24, -28, 25, 48, 46, -43, -11, -33, -19, -44, 46, -32, -22, 9, 24, -12, 12, -45, -42, -27, -34, -30, 42, -24, 46, -24, -40, 51, 33, -21, 20, 8, 19, 18, -5, 9, 10, -38, 47, -13, -34, 16, -29, 57, 9, 5, -34, 34, 10, -24, -42, 19, -48, -33, 7, 55, -18, 8, -20, 1, -25, 56, 20, -12, -18, 44, 21, -9, 24, 21, -27, -20, -12, -27, -39, -42, 58, 36, -36, 43, 31, -22, 37, -17, 52, -36, -28, 10, 4, -23, -19, -27, -43, -38, 25, -22, 16, -31, 9, 53, 17, 46, 53, 45, 52, 43, 27, 
  40, -26, -18, -7, 36, 42, -1, -22, -45, 14, -49, -42, 1, -23, 42, 8, -33, 19, 12, -7, -37, 30, -43, 14, 2, 25, 18, -27, -45, 45, 36, 19, -6, -36, -32, 35, -7, 18, -53, -24, -4, -46, 19, -6, 1, 8, -12, -44, -38, -32, 41, -41, 34, -37, 32, 40, -34, 7, -30, -4, 8, -27, 35, 0, 0, 1, 30, 52, 42, -22, -35, 14, 41, 41, 20, 27, -20, -49, -10, 29, -52, -17, -43, 31, -34, 33, -14, 30, 2, -18, -36, -7, 18, -14, 45, -12, 25, 32, -39, -43, -53, 32, -10, 42, 16, -7, 6, 15, 30, -29, 35, -8, 43, -26, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 40,114 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0036618064623326063, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,40 } };
const TfArray<1, float> quant7_scale = { 1, { 0.15281033515930176, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,20 } };
const TfArray<1, float> quant8_scale = { 1, { 0.16036719083786011, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.34115874767303467, } };
const TfArray<1, int> quant9_zero = { 1, { -16 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 114, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 60, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 160, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 4560, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 128), (TfLiteIntArray*)&g0::tensor_dimension7, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1093768_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1093768_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1093768_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1093768_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1093768_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
